### PR TITLE
419 make sfx for hestmor rolling in flesh

### PR DESCRIPTION
**Pull request by Hhk187**
Added hestmor rolling in flesh, been tested and approved by @vitormaduro and @Pseudo-64

### CODE REVIEW

**Comment by Hhk187** [comment]
seems like there is conflict huh

**Review by vitormaduro — APPROVED** [review]

**Comment by vitormaduro** [comment]
@Hhk187 There are merge conflicts with this branch. Please fix them so I can merge

**Comment by Hhk187** [comment]
how am i suppose to fix this? these are important files, its not like i can just delete them, and also what's the conflicts inside these files, because i've got no information here.

**Comment by vitormaduro** [comment]
In VS Code you can use the `git pull origin develop` command to merge the changes from `develop` into your branch. This will show you which files have conflicts and you'll be able to solve them manually

**Comment by Hhk187** [comment]
the conflict inside "Slide.cs"was a "space" -_-
image

**Comment by Hhk187** [comment]
Ok its done, i've solved the conflicts and merged. Can i delete the branches since they not useful anymore?

**Pull request merged**
